name: "FreedomChat"
version: "$version"
main: "ru.bk.oharass.freedomchat.FreedomChat"
description: "$description"
authors:
  - "oharass"
  - "sulu"
website: "https://github.com/e-im/FreedomChat"
api-version: "1.20"
folia-supported: true
