name: "FreedomChat"
version: "$version"
main: "ru.bk.oharass.freedomchat.FreedomChat"
description: "$description"
authors:
  - "oharass"
  - "sulu"
  - "ocelotpotpie"
  - "pop4959"
website: "https://github.com/ocelotpotpie/FreedomChat"
api-version: "1.21"
folia-supported: true
